# Generated by Django 4.1.3 on 2023-02-16 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('halls_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RezerwationHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='halls_app.hall')),
            ],
            options={
                'unique_together': {('date', 'hall')},
            },
        ),
    ]
