# Generated by Django 4.1.3 on 2023-02-17 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('halls_app', '0002_rezerwationhall'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RezerwationHall',
            new_name='ReservationHall',
        ),
    ]
